### ISSUE TITLE
Templates are counted as guests that seems to be down

### ISSUE THREAD

**Issue by ThomasWetzel** [Starttoaster/proxmox-exporter#40]
Hi,

thank you for your great work.

I recognized that a proxmox template is counted as down.

Perhaps you can exclude the templates?

Thank you
Thomas

**Comment by Starttoaster** [comment]
Hey Thomas, thanks for the kind words. Yeah, I actually recently noticed that myself and was thinking a bit about it. I guess from the perspective of Proxmox, a template isn't much different from a stopped VM. But I think I personally agree with treating templates as different from stopped VMs, and I can see it being problematic with alerting rules anyway. So I'll make the exporter exclude them, thanks for the Issue!

**Comment by Starttoaster** [comment]
Somewhat surprisingly, I'm not seeing an identifier in the API for a VM instance that specifies whether it's a template or a normal VM https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu

I'll keep looking around the documentation, I would assume Proxmox exposes that information in the API somewhere. But if it requires an additional API request per-VM to discover if it's a template, I might choose to make it opt-in via a flag or environment variable.

**Comment by Starttoaster** [comment]
Ah, on their /cluster/resources endpoint they expose that information (it's actually not documented but for qemu resources there's a secret `template` field that they toggle between 1 and 0, for template and not-template respectively.) https://pve.proxmox.com/pve-docs/api-viewer/index.html#/cluster/resources

I can probably carve some time to add that API request in tomorrow. This seems to be one API request per page-load, so not too expensive to make the default here.

**Comment by Starttoaster** [comment]
I believe the latest version of the exporter fixes the behavior for templates showing up as stopped VMs. Let me know if you get a chance to update and can confirm.

**Comment by Starttoaster** [comment]
Hey, thanks for bearing with me on the grafana part! I missed the re-open of this Issue for a bit. And when I found it, I was in the middle of some pressing issues at work so I put it off until a more calm time. I updated the grafana json in main with your version of the query. In your opinion, does this same feedback apply for any of the other stats at the top of the dashboard like down LXCs? I don't really use LXC at all.

**Comment by Starttoaster** [comment]
Hey, sorry for the time lapsed between your reply and my fix! Since you hadn't replied to this Issue I'm going to assume this is fully resolved for you. Please open up a new Issue or comment back/re-open this one if you have any other suggestions or issues with the exporter :)

**Comment by ThomasWetzel** [comment]
Hey,
I have two Proxmox clusters running.
In my second cluster I have LXCs both running and powered down.

Is it possible to somehow configure more than one Proxmox cluster?
I'd be happy to share my knowledge if your JSON is working with the LXCs, too.

**Comment by Starttoaster** [comment]
> Is it possible to somehow configure more than one Proxmox cluster?

I think configuring this to monitor multiple clusters may be more code overhead than is worth to maintain, to be honest. I would suggest running multiple installations of this exporter - one for each Proxmox cluster.
